#Clone the same sample project

RUN git clone  https://github.com/GrvJava/Goibibo/tree/master/SpringMVCMaven

#Go to the project directory

RUN cd SpringMVCMaven

#Deploy war file

FROM tomcat:8

ADD target/*.war /usr/local/tomcat/webapps/





